-- MySQL Script generated by MySQL Workbench
-- Wed Nov 24 09:34:23 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema csc4402db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema csc4402db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `csc4402db` DEFAULT CHARACTER SET utf8 ;
USE `csc4402db` ;

-- -----------------------------------------------------
-- Table `csc4402db`.`teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csc4402db`.`teachers` (
  `tid` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `subject` VARCHAR(45) NULL,
  `salary` DECIMAL(10,2) NULL,
  PRIMARY KEY (`tid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `csc4402db`.`clubs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csc4402db`.`clubs` (
  `name` VARCHAR(45) NOT NULL,
  `sponsor` INT NOT NULL,
  `room_number` INT NULL,
  `budget` DECIMAL(7,2) NULL,
  PRIMARY KEY (`name`),
  INDEX `sponsor_idx` (`sponsor` ASC) VISIBLE,
  CONSTRAINT `sponsor`
    FOREIGN KEY (`sponsor`)
    REFERENCES `csc4402db`.`teachers` (`tid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `csc4402db`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csc4402db`.`students` (
  `sid` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `sex` VARCHAR(45) NOT NULL,
  `year` INT NULL,
  `GPA` DECIMAL(3,2) NULL,
  `club` VARCHAR(45) NULL,
  `role` VARCHAR(45) NULL,
  PRIMARY KEY (`sid`),
  INDEX `club_idx` (`club` ASC) VISIBLE,
  CONSTRAINT `club`
    FOREIGN KEY (`club`)
    REFERENCES `csc4402db`.`clubs` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `csc4402db`.`sports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csc4402db`.`sports` (
  `sport` VARCHAR(45) NOT NULL,
  `sex` VARCHAR(45) NOT NULL,
  `division` VARCHAR(45) NOT NULL,
  `budget` DECIMAL(8,2) NULL,
  `head_coach` INT NOT NULL,
  PRIMARY KEY (`sport`, `sex`, `division`),
  INDEX `head_coach_idx` (`head_coach` ASC) VISIBLE,
  CONSTRAINT `head_coach`
    FOREIGN KEY (`head_coach`)
    REFERENCES `csc4402db`.`teachers` (`tid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `csc4402db`.`players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csc4402db`.`players` (
  `sid` INT NOT NULL,
  `sport` VARCHAR(45) NOT NULL,
  `division` VARCHAR(45) NOT NULL,
  `sex` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sid`, `sport`, `division`, `sex`),
  INDEX `sport_idx` (`sport` ASC, `division` ASC, `sex` ASC) VISIBLE,
  CONSTRAINT `sid`
    FOREIGN KEY (`sid`)
    REFERENCES `csc4402db`.`students` (`sid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sport`
    FOREIGN KEY (`sport` , `division` , `sex`)
    REFERENCES `csc4402db`.`sports` (`sport` , `division` , `sex`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
