-- MySQL Script generated by MySQL Workbench
-- Wed Nov 24 11:16:22 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema csc4402db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema csc4402db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `csc4402db` DEFAULT CHARACTER SET utf8 ;
USE `csc4402db` ;

-- -----------------------------------------------------
-- Table `csc4402db`.`teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csc4402db`.`teachers` (
  `tid` INT NOT NULL,
  `fname` VARCHAR(45) NULL,
  `lname` VARCHAR(45) NULL,
  `subject` VARCHAR(45) NULL,
  `salary` DECIMAL(10,2) NULL,
  PRIMARY KEY (`tid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `csc4402db`.`clubs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csc4402db`.`clubs` (
  `name` VARCHAR(45) NOT NULL,
  `sponsor` INT NOT NULL,
  `room_number` INT NULL,
  `budget` DECIMAL(7,2) NULL,
  PRIMARY KEY (`name`),
  INDEX `sponsor_idx` (`sponsor` ASC) VISIBLE,
  CONSTRAINT `sponsor`
    FOREIGN KEY (`sponsor`)
    REFERENCES `csc4402db`.`teachers` (`tid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `csc4402db`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csc4402db`.`students` (
  `sid` INT NOT NULL,
  `fname` VARCHAR(45) NULL,
  `lname` VARCHAR(45) NULL,
  `sex` VARCHAR(45) NOT NULL,
  `year` INT NULL,
  `GPA` DECIMAL(3,2) NULL,
  `club` VARCHAR(45) NULL,
  `role` VARCHAR(45) NULL,
  PRIMARY KEY (`sid`),
  INDEX `club_idx` (`club` ASC) VISIBLE,
  CONSTRAINT `club`
    FOREIGN KEY (`club`)
    REFERENCES `csc4402db`.`clubs` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `csc4402db`.`sports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csc4402db`.`sports` (
  `sport` VARCHAR(45) NOT NULL,
  `sex` VARCHAR(45) NOT NULL,
  `division` VARCHAR(45) NOT NULL,
  `budget` DECIMAL(8,2) NULL,
  `head_coach` INT NOT NULL,
  PRIMARY KEY (`sport`, `sex`, `division`),
  INDEX `head_coach_idx` (`head_coach` ASC) VISIBLE,
  CONSTRAINT `head_coach`
    FOREIGN KEY (`head_coach`)
    REFERENCES `csc4402db`.`teachers` (`tid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `csc4402db`.`players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csc4402db`.`players` (
  `sid` INT NOT NULL,
  `sport` VARCHAR(45) NOT NULL,
  `sex` VARCHAR(45) NOT NULL,
  `division` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sid`, `sport`, `sex`, `division`),
  INDEX `sport_idx` (`sport` ASC, `division` ASC, `sex` ASC) VISIBLE,
  CONSTRAINT `sid`
    FOREIGN KEY (`sid`)
    REFERENCES `csc4402db`.`students` (`sid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sport`
    FOREIGN KEY (`sport` , `division` , `sex`)
    REFERENCES `csc4402db`.`sports` (`sport` , `division` , `sex`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `csc4402db`.`teachers`
-- -----------------------------------------------------
START TRANSACTION;
USE `csc4402db`;
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (tid, 'fname', 'lname', 'subject', salary);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1001, 'John', 'Smith', 'Art', 87225.73);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1002, 'Beth', 'Johnson', 'Geography', 53146.61);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1003, 'Mike', 'Williams', 'Art', 84750.17);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1004, 'John', 'Brown', 'English', 44048.76);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1005, 'Karen', 'Jones', 'Dance', 36395.73);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1006, 'Nick', 'Miller', 'Spanish', 90220.46);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1007, 'Rachel', 'Davis', 'Chemistry', 83319.54);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1008, 'James', 'Garcia', 'Art', 90186.64);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1009, 'Todd', 'Rodriguez', 'PE', 66760.7);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1010, 'Tracy', 'Wilson', 'Art', 59474.79);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1011, 'Todd', 'Martinez', 'Speech', 67127);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1012, 'Robert', 'Anderson', 'French', 47116.06);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1013, 'Michelle', 'Taylor', 'Algebra', 63570.75);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1014, 'Nicole', 'Thomas', 'Calculus', 83979.25);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1015, 'Ross', 'Hernandez', 'Chemistry', 38441.96);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1016, 'Martha', 'Moore', 'History', 70556.27);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1017, 'Richard', 'Martin', 'Psychology', 31180.52);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1018, 'Anthony', 'Jackson', 'Nutrition', 94638.49);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1019, 'James', 'Thompson', 'Chemistry', 73320.89);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1020, 'Jordan', 'White', 'Health', 66448.29);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1021, 'Sandra', 'Lopez', 'Algebra', 44799.36);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1022, 'Lisa', 'Lee', 'English', 40650.89);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1023, 'Elizabeth', 'Gonzalez', 'Spanish', 67206.26);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1024, 'Anthony', 'Harris', 'Art', 82575.72);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1025, 'Lilly', 'Clark', 'Geography', 49191.66);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1026, 'Anthony', 'Lewis', 'German', 96210.17);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1027, 'Karen', 'Robinson', 'German', 87657.11);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1028, 'Sharon', 'Walker', 'Choir', 34410.46);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1029, 'Bryce', 'Perez', 'Speech', 67207.98);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1030, 'Clare', 'Hall', 'English', 87829.71);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1031, 'Laura', 'Young', 'Physics', 42558.36);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1032, 'Michelle', 'Allen', 'Algebra', 81207.55);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1033, 'Emma', 'Sanchez', 'Music', 75497.86);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1034, 'Josh', 'Wright', 'Nutrition', 89434.49);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1035, 'Deborah', 'King', 'Psychology', 87497.37);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1036, 'Clare', 'Scott', 'Algebra', 49832.49);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1037, 'Todd', 'Green', 'Physics', 77312.6);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1038, 'Tracy', 'Baker', 'Psychology', 66100.98);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1039, 'Lisa', 'Adams', 'Physics', 32032.54);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1040, 'Carol', 'Nelson', 'Music', 98604.53);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1041, 'Carol', 'Hill', 'Music', 79303.96);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1042, 'Anthony', 'Ramirez', 'Statistics', 43965.91);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1043, 'Elizabeth', 'Campbell', 'PE', 94426.22);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1044, 'Kirsten', 'Mitchell', 'German', 34234.64);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1045, 'Lisa', 'Roberts', 'Music', 56045.93);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1046, 'James', 'Carter', 'Physics', 38945.32);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1047, 'Ruth', 'Phillips', 'French', 90550.62);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1048, 'Mark', 'Evans', 'Statistics', 47011.01);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1049, 'Richard', 'Turner', 'English', 50647.74);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1050, 'Sandra', 'Torres', 'Nutrition', 64414.96);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1051, 'Abby', 'Parker', 'Dance', 50670.24);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1052, 'Josh', 'Collins', 'Calculus', 53762.42);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1053, 'Laura', 'Edwards', 'English', 41610.78);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1054, 'Elizabeth', 'Stewart', 'Dance', 35032.83);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1055, 'Deborah', 'Flores', 'Dance', 82064.79);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1056, 'Beth', 'Morris', 'Music', 89851.78);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1057, 'James', 'Nguyen', 'English', 79969.52);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1058, 'Sharon', 'Murphy', 'English', 38947.22);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1059, 'Ross', 'Rivera', 'Nutrition', 98256.73);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1060, 'Ross', 'Cook', 'Algebra', 50426.82);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1061, 'Clare', 'Rogers', 'Physics', 57086.59);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1062, 'Helen', 'Morgan', 'Geography', 54374.33);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1063, 'Karen', 'Peterson', 'English', 50152.37);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1064, 'Mike', 'Cooper', 'Nutrition', 35649.29);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1065, 'Bryce', 'Reed', 'Psychology', 57526.1);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1066, 'Josh', 'Bailey', 'Psychology', 94534.81);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1067, 'Elizabeth', 'Bell', 'English', 49302.9);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1068, 'Bryce', 'Gomez', 'Music', 79282.72);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1069, 'Anthony', 'Kelly', 'PE', 94317.28);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1070, 'Karen', 'Howard', 'Geography', 62485.55);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1071, 'Emma', 'Ward', 'Spanish', 48893.68);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1072, 'Deborah', 'Cox', 'English', 43009.97);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1073, 'Ashley', 'Diaz', 'English', 76742.75);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1074, 'Karen', 'Richardson', 'French', 52263.73);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1075, 'Helen', 'Wood', 'German', 65277.18);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1076, 'Bryce', 'Watson', 'Geography', 83492.35);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1077, 'James', 'Brooks', 'Music', 90769.35);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1078, 'Deborah', 'Bennett', 'English', 40634.68);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1079, 'Michelle', 'Gray', 'Health', 72288.35);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1080, 'Catherine', 'James', 'Physics', 96338.28);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1081, 'Bryce', 'Reyes', 'Geography', 37994);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1082, 'Ashley', 'Cruz', 'Psychology', 84266.79);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1083, 'Lisa', 'Hughes', 'Psychology', 65935.25);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1084, 'Emma', 'Price', 'Music', 94303.34);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1085, 'Ashley', 'Myers', 'Music', 47787.4);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1086, 'Ashley', 'Long', 'English', 95890.93);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1087, 'Carol', 'Foster', 'Psychology', 79624.53);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1088, 'Richard', 'Sanders', 'Spanish', 86337.58);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1089, 'Lisa', 'Ross', 'Choir', 51190.3);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1090, 'Robert', 'Morales', 'Algebra', 59492.97);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1091, 'Mike', 'Powell', 'Physics', 58166.92);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1092, 'Lisa', 'Sullivan', 'Algebra', 70413.28);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1093, 'Elizabeth', 'Russell', 'Physics', 82994.47);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1094, 'Karen', 'Ortiz', 'Biology', 69500.73);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1095, 'Todd', 'Jenkins', 'Dance', 68108.86);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1096, 'Helen', 'Gutierrez', 'Art', 51987.06);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1097, 'Nick', 'Perry', 'French', 65676.08);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1098, 'Nicole', 'Butler', 'Calculus', 41019.94);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1099, 'James', 'Barnes', 'Choir', 73886.88);
INSERT INTO `csc4402db`.`teachers` (`tid`, `fname`, `lname`, `subject`, `salary`) VALUES (1100, 'Bob', 'Fisher', 'Art', 90521.35);

COMMIT;

